services:
  postgres:
    image: postgres:16-alpine
    container_name: ansab-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ansab
    ports:
      - "5433:5432"
    volumes:
      - ansab_pgdata:/var/lib/postgresql/data
      - ./server/src/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  ansab_pgdata:
